# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-15 11:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gmina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(default='-', max_length=30)),
                ('rodzaj', models.CharField(choices=[('WIES', 'wieś'), ('MIASTO', 'miasto'), ('STATKI', 'statki'), ('ZAGRANICA', 'zagranica')], default='MIASTO', max_length=30)),
                ('liczba_mieszkancow', models.IntegerField(default=0)),
                ('liczba_uprawnionych', models.IntegerField(default=0)),
                ('liczba_wydanych_kart', models.IntegerField(default=0)),
                ('liczba_glosow_oddanych_na_kandydata_nr_1', models.IntegerField(default=0)),
                ('liczba_glosow_oddanych_na_kandydata_nr_2', models.IntegerField(default=0)),
                ('data_modyfikacji', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Kandydat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=20)),
                ('nazwisko', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Wojewodztwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='gmina',
            name='wojewodztwo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projekt_zaliczeniowy.Wojewodztwo'),
        ),
        migrations.AlterUniqueTogether(
            name='gmina',
            unique_together=set([('wojewodztwo', 'nazwa')]),
        ),
    ]
