# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-15 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projekt_zaliczeniowy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WojewodztwoRodzaj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rodzaj', models.CharField(choices=[('WIES', 'wieś'), ('MIASTO', 'miasto'), ('STATKI', 'statki'), ('ZAGRANICA', 'zagranica')], default='MIASTO', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='WojewodztwoRozmiar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
