# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-15 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projekt_zaliczeniowy', '0002_wojewodztworodzaj_wojewodztworozmiar'),
    ]

    operations = [
        migrations.AddField(
            model_name='wojewodztworozmiar',
            name='dolny_limit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wojewodztworozmiar',
            name='gorny_limit',
            field=models.IntegerField(default=0),
        ),
    ]
